### ISSUE TITLE
Epic - Improve Android Attachments API

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#2935]
Given that this is an epic, it's related to Core and both of the UI SDKs. 

### Context & proposal

Our attachments API is one of the most important parts of the messaging experience and we need to add more efforts into improving it.

This includes improving the performance of attachment items, allowing for aspect ratio/resizability when it comes to images and giphies, providing more supported attachment types, syncing attachments between SDKs and more.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] #2911 Sync attachments between SDKs on Compose.
- [ ] #2886 Implement attachment resizing in UI Components. (We should mirror this behavior for Compose too.
- [ ] #2816 Make sure our attachments/integrations are properly disabled with given composer input.
- [ ] Disable editing from attachment-only messages (to mitigate issues) or enable editing, but take into consideration removing attachments from an edited message.
- [ ] #2680 Implement attachment UI/UX changes based on the design.
- [ ] #2623 Cover custom attachment factories in Compose in a guide in our documentation.
- [ ] #2238 Improve the quoted message experience in Compose (related to attachments).
- [ ] #2876 & #2166 Support customizable mime/file types in attachments.
