### ISSUE TITLE
Epic - Improve SDK configuration options

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#2937]
Given that this is an epic, it's related to Core and both of the UI SDKs.

### Context & proposal

We have the ability to customize supported features and data in our app through the dashboard configuration.

We can support and customize the following:
- Channel capabilities -> the features which are supported for a given channel
- Supported attachments (as described in #2935)
- Custom components for specific use cases (e.g. Livestream message list)
- Date/time customization

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] #2922 In Core.
- [ ] #2297 in Compose and XML.
- [ ] #2166 #2876 As described in another epic.
- [ ] #2126 Creating a more concrete livestream app and pulling customization for optimal experience out into the SDK.
- [ ] #2883 Add customizable date/time formatters.
- [ ] #2936 Provide livestream component variants that are optimized.
